-   id: stylelint
    name: stylelint
    description: 'A CSS linter.'
    entry: stylelint
    language: node
    'files': \.(css|scss|sass)$
    args: []
    require_serial: false
    additional_dependencies: ["stylelint@14.9.0"]
    minimum_pre_commit_version: '0'
